import { Link, useParams } from "react-router-dom";
import DashboardTemplate from "@/components/templates/DashboardTemplate";
import InfoCard from "@/components/molecules/InfoCard";
import EmptyState from "@/components/molecules/EmptyState";
import { useParentBilling, useParentChildren, useParentDashboard, useParentNotifications, useParentResource, useStudentDashboard, useStudentNotifications, useStudentProfile, useStudentResource } from "@/features/portal/hooks";

const value = (v: unknown) => v == null ? "—" : typeof v === "object" ? JSON.stringify(v) : String(v);
function DataList({ data }: { data: unknown }) { const rows = Array.isArray(data) ? data : (data as { items?: unknown[] })?.items ?? []; if (!rows.length) return <EmptyState title="Nothing to show yet" description="Your school has not published any records here." />; return <div className="space-y-3">{rows.map((row, i) => <InfoCard key={i}><div className="grid gap-2 text-sm sm:grid-cols-2 lg:grid-cols-3">{Object.entries(row as Record<string, unknown>).filter(([, v]) => typeof v !== "object" || v == null).map(([k, v]) => <div key={k}><span className="capitalize text-[var(--color-text-muted)]">{k.replace(/([A-Z])/g, " $1")}</span><p className="font-medium">{value(v)}</p></div>)}</div></InfoCard>)}</div> }
function StudentEnrollment({ children }: { children: (id?: string) => React.ReactNode }) { const profile = useStudentProfile(); const enrollment = profile.data?.enrollments?.[0]?.enrollmentId; return <>{children(enrollment)}</>; }
export function StudentDashboardPage() { return <StudentEnrollment>{id => <StudentDashboard enrollmentId={id} />}</StudentEnrollment>; }
function StudentDashboard({ enrollmentId }: { enrollmentId?: string }) { const q = useStudentDashboard(enrollmentId); if (!enrollmentId) return <DashboardTemplate title="My dashboard"><EmptyState title="No current enrollment" description="Please contact your school administrator." /></DashboardTemplate>; const d = q.data; return <DashboardTemplate title={`Welcome${d ? `, ${d.firstName}` : ""}`} subtitle="Here is your school day at a glance." loading={q.isLoading}><div className="grid gap-4 md:grid-cols-4">{[["Attendance", d?.attendancePercentage ? `${d.attendancePercentage}%` : "—"], ["Overall grade", d?.overallGrade ?? "—"], ["Unread notices", d?.unreadNotificationCount ?? 0], ["Class", d?.classRoomName ?? "—"]].map(([t,v]) => <InfoCard key={t}><p className="text-sm text-[var(--color-text-secondary)]">{t}</p><p className="mt-2 text-2xl font-semibold">{v}</p></InfoCard>)}</div><div className="mt-6 grid gap-6 lg:grid-cols-2"><InfoCard title="Today’s lessons"><DataList data={d?.todaySchedule} /></InfoCard><InfoCard title="Upcoming assignments"><DataList data={d?.upcomingAssignments} /></InfoCard></div></DashboardTemplate>; }
export function StudentResourcePage({ title, resource }: { title: string; resource: string }) { return <StudentEnrollment>{id => <StudentResource title={title} resource={resource} enrollmentId={id} />}</StudentEnrollment>; }
function StudentResource({ title, resource, enrollmentId }: { title: string; resource: string; enrollmentId?: string }) { const q = resource === "notifications" ? useStudentNotifications() : useStudentResource(enrollmentId, resource); return <DashboardTemplate title={title} loading={q.isLoading}><DataList data={q.data} /></DashboardTemplate>; }
export function ParentDashboardPage() { const q = useParentDashboard(); const d = q.data; return <DashboardTemplate title="Family dashboard" subtitle="Your children’s school day at a glance." loading={q.isLoading}><div className="grid gap-4 md:grid-cols-3"><InfoCard><p className="text-sm text-[var(--color-text-secondary)]">Children</p><p className="mt-2 text-2xl font-semibold">{d?.children?.length ?? 0}</p></InfoCard><InfoCard><p className="text-sm text-[var(--color-text-secondary)]">Unread notices</p><p className="mt-2 text-2xl font-semibold">{d?.unreadNotificationCount ?? 0}</p></InfoCard><InfoCard><p className="text-sm text-[var(--color-text-secondary)]">Balance due</p><p className="mt-2 text-2xl font-semibold">{d?.totalBalanceDue ?? 0}</p></InfoCard></div><div className="mt-6 grid gap-4 md:grid-cols-2">{d?.children?.map((child: Record<string, unknown>) => <Link key={String(child.studentId)} to={`/parent/children/${child.studentId}`}><InfoCard><h2 className="text-lg font-semibold">{String(child.firstName)} {String(child.lastName)}</h2><p className="mt-1 text-sm text-[var(--color-text-secondary)]">{String(child.currentClass ?? "Current class unavailable")}</p><p className="mt-4 text-sm">Attendance: <b>{String(child.attendancePercentage ?? "—")}%</b> · Pending work: <b>{String(child.pendingAssignments ?? 0)}</b></p></InfoCard></Link>)}</div></DashboardTemplate>; }
export function ParentChildrenPage() { const q = useParentChildren(); return <DashboardTemplate title="My children" loading={q.isLoading}><div className="grid gap-4 md:grid-cols-2">{(q.data ?? []).map((child: Record<string, unknown>) => <Link key={String(child.studentId)} to={`/parent/children/${child.studentId}`}><InfoCard><h2 className="text-lg font-semibold">{String(child.firstName)} {String(child.lastName)}</h2><p className="text-sm text-[var(--color-text-secondary)]">{String(child.currentClass ?? "")}</p></InfoCard></Link>)}</div></DashboardTemplate>; }
export function ParentResourcePage({ title, resource }: { title: string; resource: string }) { const { studentId } = useParams(); const q = resource === "notifications" ? useParentNotifications() : resource === "billing" ? useParentBilling() : useParentResource(studentId, resource); return <DashboardTemplate title={title} loading={q.isLoading}>{resource === "profile" && studentId && <div className="mb-6 flex flex-wrap gap-2">{[["Attendance", "attendance"], ["Grades", "grades"], ["Assignments", "assignments"], ["Report cards", "report-cards"]].map(([label, path]) => <Link key={path} to={`/parent/children/${studentId}/${path}`} className="rounded-lg bg-[var(--color-primary-light)] px-3 py-2 text-sm font-medium text-[var(--color-primary)]">{label}</Link>)}</div>}<DataList data={q.data} /></DashboardTemplate>; }
